### PR TITLE
update PYROOT setting, timeOut setting, and env setup file, add run file

### PR DESCRIPTION
**Pull request by shaochenghua**
I remove the local folder names from the setup parameters, so the code cannot work directly on any RCSB server without explicitly setting up several parameters.

### CODE REVIEW

**Comment by piehld** [comment]
Thanks @shaochenghua. The two additional files you'll need to update are:
- https://github.com/rcsb/py-rcsb_ccmodels/blob/master/rcsb/ccmodels/search/__init__.py - increment the version number
- https://github.com/rcsb/py-rcsb_ccmodels/blob/master/HISTORY.txt - add a line with the new version and summary of changes

Also, are you planning to use this package as installed from PyPI, or installed with the repo (i.e., by pulling the repo and installing locally)? If the former, I'm not exactly sure yet how John was pushing the updated package versions to PyPI...I'm guessing he was doing it manually, but I'm not sure of the command. Usually, for our other Python packages, we use Azure pipelines to publish to PyPI, which we could set up here too, though that will require a bit of work.

**Comment by shaochenghua** [comment]
Thx Dennis. Updated version. The work highly depends on RCSB infrastructure, not sure why John set it public. 
Anyhow, I did installation directly from this repo, not PyPI. There was indeed a PyPI, but John didn't update with the latest code, i.e. before I modified it, it was already out of syn with PyPI. 
Please free free to publish it on PyPI. If you go through Azure, I'm not sure the code (before my update) will pass the style checking.

**Review by piehld — APPROVED** [review]
Thanks for the updates @shaochenghua, your changes LGTM. 

Also, if you don't need it to be pushed to PyPI, I'll probably defer to trying to do that later since it will take me some time to figure out how to do so.

**Comment by shaochenghua** [comment]
What does LGTM mean?
I don't need this in PyPI for now. Feel free to do it later.

**Comment by shaochenghua** [comment]
Lets get this merged

**Comment by piehld** [comment]
LGTM is Looks good to me :)

**Pull request merged**
